-- MySQL Script generated by MySQL Workbench
-- 12/30/14 01:31:49
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema waw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `waw` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `waw` ;

-- -----------------------------------------------------
-- Table `waw`.`FILM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waw`.`FILM` (
  `FID` INT NOT NULL,
  `FTitel` VARCHAR(45) NULL,
  `Regie` VARCHAR(45) NULL,
  `Schauspieler` VARCHAR(45) NULL,
  `Erscheinungsjahr` VARCHAR(45) NULL,
  `Drehbuch` VARCHAR(45) NULL,
  `fav` TINYINT(1) NULL,
  `Genre` VARCHAR(45) NULL,
  PRIMARY KEY (`FID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waw`.`ALBUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waw`.`ALBUM` (
  `AID` INT NOT NULL,
  `ATitel` VARCHAR(45) NULL,
  `Jahr` VARCHAR(45) NULL,
  `Songs` VARCHAR(45) NULL,
  `Interpreter` VARCHAR(45) NULL,
  `fav` TINYINT(1) NULL,
  `Genre` VARCHAR(45) NULL,
  PRIMARY KEY (`AID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
